### ISSUE TITLE
error if batch size =1

### ISSUE THREAD

**Issue by mzaiady** [charlesq34/pointnet#32]
Hi..

I'm getting the following error error while trying to change batch size to 1

`python evaluate.py --visu --batch_size 1
`

```
.....
......
ValueError: Shape must be rank 2 but is rank 3 for 'MatMul_1' (op: 'MatMul') with input shapes: [1024,64], [1,64,64].

```
My final goal is to  call the network to predicted from data input from Depth sensor (e.g. Kinect)

I'm trying to call it with only one point cloud and see what it will predict, any idea how to achieve that!  

modifying the code and changing  batch size to None, so it should depend on actual input, results in different error!

`TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, -1]. Consider casting elements to a supported type.
`

**Comment by charlesq34** [comment]
Hi @mzaiady 

Thanks for pointing out this bug. I've just fixed it -- should work now!

Best,
Charles

**Comment by mf27** [comment]
Has this really solved the problem?
I still can't get it to work with variable batch size...
@mzaiady , it works for you?
